name: holerite
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_masked_text: ^0.8.0
  get: ^4.1.4
  google_fonts: ^2.0.0
  http: ^0.13.3
  printing: ^5.2.1
  syncfusion_flutter_pdfviewer: ^19.1.59-beta
  url_launcher: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/beta.jpg
    - assets/junho/
    - assets/maio/
    - assets/julho/
